### ISSUE TITLE
请问原始的文本的数据怎么进行ＢI O标注，有这部分处理的代码吗

### ISSUE THREAD

**Issue by Owenscu** [kifish/NER-demo#1]
![image](https://user-images.githubusercontent.com/23129979/55711175-c27cfa80-5a1e-11e9-8c3b-d79d5c12a017.png)

**Comment by kifish** [comment]
这是某门课程作业的实验数据。据我分析，助教应该是在SIGHANBakeoff2006中文NER数据集上做了处理，你可以用这份数据集的名称google一下。

**Comment by Owenscu** [comment]
@kifish 谢谢哈，我自己谢了
